### ISSUE TITLE
Example Study #3

### ISSUE THREAD

**Issue by huyagci** [huyagci/perdev#14]
### Tasks

- [x] Task 1
- [x] Task 2
- [ ] Task 3
- [ ] Task 4
- [ ] Task 5

Hola.

### Practice Project

[Summary Notes](https://github.com/users/huyagci/projects/1)

### Controls

- [X] Don't forget to choose additional labels.
- [X] Don't forget to add issue to project board.
- [X] Don't forget to select a milestone regarding of the status of the project.
